name: Deploy coverage report to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  coverage:
    environment:
      name: github-pages
      url: ${{ steps.pages-deploy.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout & setup
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # 2. Build & test
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
      - run: npx lcov-badge2 .tap/report/lcov.info -o .tap/report/badge.svg

      # 3. (Optional) upload raw artifact for other jobs
      - name: Upload raw coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: .tap/report

      # 4. Package for Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .tap/report

      # 5. Deploy to Pages
      - name: Deploy to GitHub Pages
        id: pages-deploy
        uses: actions/deploy-pages@v4
