name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Linting with ESLint
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: npm install
      - run: npx eslint .
      - run: npx tsc -p jsconfig.json
      - run: npm test
